get http://localhost:3000/todos/?status=TO%20DO

Content-Type: application/json

[
{
        "id": 2,
        "todo": "Buy a Car",
        "priority": "MEDIUM",
        "status": "TO DO",
        "category": "HOME",
        "dueDate": "2021-09-22"
      },
]

###
get http://localhost:3000/todos/?search_q=Buy

Content-Type: application/json


[
      {
        "id": 1,
        "todo": "Learn Node JS",
        "priority": "HIGH",
        "status": "IN PROGRESS",
        "category": "LEARNING",
        "dueDate": "2021-03-16"
      },
      ...
    ]

    ###

get http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

Content-Type: application/json


    [
      {
        "id": 1,
        "todo": "Learn Node JS",
        "priority": "HIGH",
        "status": "IN PROGRESS",
        "category": "LEARNING",
        "dueDate": "2021-03-16"
      },
      ...
    ]
###

get http://localhost:3000/todos/?search_q=Buy

Content-Type: application/json


 [
      {
        "id": 2,
        "todo": "Buy a Car",
        "priority": "MEDIUM",
        "status": "TO DO",
        "category": "HOME",
        "dueDate": "2021-09-22"
      },
      ...
    ]

    ###
get http://localhost:3000/todos/?category=WORK&status=DONE

Content-Type: application/json


 [
      {
        "id": 4,
        "todo": "Fix the bug",
        "priority": "MEDIUM",
        "status": "DONE",
        "category": "WORK",
        "dueDate": "2021-01-25"
      },
      ...
    ]

    ###
get http://localhost:3000/todos/?category=HOME

Content-Type: application/json

  [
      {
        "id": 2,
        "todo": "Buy a Car",
        "priority": "MEDIUM",
        "status": "TO DO",
        "category": "HOME",
        "dueDate": "2021-09-22"
      },
      ...
    ]

get http://localhost:3000/todos/?category=LEARNING&priority=HIGH

Content-Type: application/json


 [
      {
        "id": 1,
        "todo": "Learn Node JS",
        "priority": "HIGH",
        "status": "IN PROGRESS",
        "category": "LEARNING",
        "dueDate": "2021-03-16"
      },
      ...
    ]

  #########

  
get http://localhost:3000/todos/2/

###

get http://localhost:3000/agenda/?date=2021-12-12

###
post http://localhost:3000/todos/

Content-Type : application/json

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}
```
####
delete http://localhost:3000/todos/1/

###

put http://localhost:3000/todos/1/

Content-Type: application/json
 {
      "status": "DONE"
    }
    ###


put http://localhost:3000/todos/1/

Content-Type: application/json

    {
      "priority": "HIGH"
    }
    ```
    ###
    put http://localhost:3000/todos/1/

Content-Type: application/json

    {
      "todo": "Clean the garden"
    }
    ```
    ###
    put http://localhost:3000/todos/1/

Content-Type: application/json

  {
      "category": "LEARNING"
    }
    ```

    ####
      put http://localhost:3000/todos/1/

Content-Type: application/json

 {
      "dueDate": "2021-01-12"
    }
    ```

  
  

